### ISSUE TITLE
Expecting length, unexpected value found

### ISSUE THREAD

**Issue by Pavel-Sayekat** [vishwenga/Simple-Python-TwitterBot#2]
On parabola-arch the script frequently fails showing this "Expecting length, unexpected value found" message after every 2 or 3 retweets. But on Ubuntu, the grequency of failing is less. Any guess? Using python2 for this script.

**Comment by vishwenga** [comment]
Sorry I tried to recreate your issue, but i couldn't.

**Comment by Pavel-Sayekat** [comment]
Ok, the script runs smooth on python 3 and also on Ubuntu I noticed that the script is running on python 3 by default as the python-tweepy package on Ubuntu supports both as a single package. The issue appears when I use python 2 and on arch there are two separate packages as python2-tweepy and python3-tweepy. So I had to tell the script to use python 3 on arch, problem solved :)
